### ISSUE TITLE
Display issues with SerialPOS VFD and German umlauts

### ISSUE THREAD

**Issue by QBJack** [herrnst/script.xbmc.lcdproc#36]
Hello,

I have two serialPOS VFDs 2x20 and for both I cannot get them to display correct chars. Mostly it's a problem with German umlauts, they are displayed then as an "?" or "-". Both displays are configuarble for different charsets and regions with the manufacturer's tool, so I can set different emulations and so on. There is one settings that works with German umlauts but then the menu items of Kodi are displayed this way: "ÄSystem-AddonsÜ". It should be something like "[System-Addons]" I think. Can you please take a look into it? I am also using a HD44780 based LCD2USB display and this one works like expected. I am using OpenElec 5.0.8 and the latest 6.0 Beta of OpenElec so modifications to the system are limited.
The serialPOS I am testing on right now is set to WPC1252, CD5220 emulation and German codepage. These settings give me the best results. XMC LCDproc is set to default charset. Other settings make it even worse.

Thanks and regards
Thomas

**Comment by herrnst** [comment]
Umm, I'm not sure how to help here since I don't own such a display. That's probably something with the character mapping either in the addon, LCDproc, the display or even a combination of all three components. An option might be to setup LCDproc to not parse/convert characters (charmap = raw/none) and then implement a separate mapping for the addon (there are two custom conversion maps for HD44780-A00 and -A02 displays, so another map for this display type is quickly done). If it finally works, instructions on how to set things up once it works would be great.

**Comment by QBJack** [comment]
Any help is welcome. I have no idea where to start...

**Comment by UmpPCPL** [comment]
I know that issue is quite old but maybe it will help somebody.
This problem can be easily fixed.
See my unaccepted pull request:
https://github.com/herrnst/script.xbmc.lcdproc/pull/33
and issues
https://github.com/herrnst/script.xbmc.lcdproc/issues/26  ( not mine )
https://github.com/herrnst/script.xbmc.lcdproc/issues/23 (mine)

"LCD Addon would translate UTF-8 to CP852 and then
lcdproc would pass it directly to VFD.

Without this change all unknown characters are translated to
"?" by LCD Addon and there is no way to fix it later in lcdproc."
